---
name: kong

director_uuid: 63ddb6a6-d6fe-40e1-b16b-2ff6b2034c79

instance_groups:
- name: kong
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: kong
    release: kong
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: kong
  version: latest # TODO: update after first final release
  # url:            TODO: update after first final release
  # sha1:           TODO: update after first final release
